# Starship Configuration file
# https://starship.rs/config/

# General Prompt Settings
add_newline = false

# Module Settings

[aws]
symbol = " "

[bun]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os.symbols]
Macos = " "
Ubuntu = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[zig]
symbol = " "


